from genlayer_py.chains.localnet import SIMULATOR_JSON_RPC_URL


GLTEST_CONFIG_FILE = "gltest.config.yaml"
DEFAULT_NETWORK = "localnet"
DEFAULT_RPC_URL = SIMULATOR_JSON_RPC_URL
DEFAULT_ENVIRONMENT = ".env"
DEFAULT_CONTRACTS_DIR = "contracts"
DEFAULT_NETWORK_ID = 61999
