name: Tests

on:
  workflow_call:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test-with-python:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v6

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup | Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Setup | Install dependencies
        run: uv sync --python ${{ matrix.python-version }}

      - name: Action | Run gltest cli tests
        run: uv run gltest tests/gltest_cli/

      - name: Action | Run gltest tests
        run: uv run gltest tests/gltest/
